{"stats": {"errors": 6, "failures": 0, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 6}, "results": [{"classname": "index_test:TestSchema", "name": "test_alive_column", "time": 0.00034880638122558594, "type": "error", "errtype": "builtins.IndexError", "message": "list index out of range", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/BillyPittman1993/sqlalchemy-mapping-and-schema-lab-staff/test/index_test.py\", line 37, in test_alive_column\n    name = self.table_info[4][1]\nIndexError: list index out of range\n"}, {"classname": "index_test:TestSchema", "name": "test_dob_column", "time": 0.00032639503479003906, "type": "error", "errtype": "builtins.IndexError", "message": "list index out of range", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/BillyPittman1993/sqlalchemy-mapping-and-schema-lab-staff/test/index_test.py\", line 31, in test_dob_column\n    name = self.table_info[3][1]\nIndexError: list index out of range\n"}, {"classname": "index_test:TestSchema", "name": "test_fullname_column", "time": 0.00031447410583496094, "type": "error", "errtype": "builtins.IndexError", "message": "list index out of range", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/BillyPittman1993/sqlalchemy-mapping-and-schema-lab-staff/test/index_test.py\", line 19, in test_fullname_column\n    name = self.table_info[1][1]\nIndexError: list index out of range\n"}, {"classname": "index_test:TestSchema", "name": "test_id_column", "time": 0.0002453327178955078, "type": "error", "errtype": "builtins.IndexError", "message": "list index out of range", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/BillyPittman1993/sqlalchemy-mapping-and-schema-lab-staff/test/index_test.py\", line 13, in test_id_column\n    name = self.table_info[0][1]\nIndexError: list index out of range\n"}, {"classname": "index_test:TestSchema", "name": "test_instrument_column", "time": 0.00023818016052246094, "type": "error", "errtype": "builtins.IndexError", "message": "list index out of range", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/BillyPittman1993/sqlalchemy-mapping-and-schema-lab-staff/test/index_test.py\", line 25, in test_instrument_column\n    name = self.table_info[2][1]\nIndexError: list index out of range\n"}, {"classname": "index_test:TestSchema", "name": "test_table_name", "time": 0.0002713203430175781, "type": "error", "errtype": "builtins.TypeError", "message": "'NoneType' object is not subscriptable", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/BillyPittman1993/sqlalchemy-mapping-and-schema-lab-staff/test/index_test.py\", line 10, in test_table_name\n    self.assertEqual(cursor.execute(\"SELECT name FROM sqlite_master WHERE type='table';\").fetchone()[0], 'musicians')\nTypeError: 'NoneType' object is not subscriptable\n"}]}